name: Lint Front-end

on:
  push:
    branches:
      - main # Or your default branch like master
  pull_request:
    branches:
      - main # Or your default branch like master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Or a specific version compatible with your linters

    - name: Install linters
      run: |
        npm install -g htmlhint stylelint eslint

    - name: Lint HTML
      run: htmlhint "app/src/main/resources/static/assets/pages/**/*.html" || true

    - name: Lint CSS
      run: stylelint "app/src/main/resources/static/assets/css/**/*.css" || true

    - name: Lint JavaScript
      run: eslint "app/src/main/resources/static/assets/js/**/*.js" || true
